name: base
channels:
  - r
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=2020.07
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - _r-mutex=1.0.0
  - adal=1.2.6
  - alabaster=0.7.12
  - anaconda=custom
  - anaconda-client=1.7.2
  - anaconda-navigator=1.10.0
  - anaconda-project=0.9.1
  - ansiwrap=0.8.4
  - anyio=2.2.0
  - applaunchservices=0.2.1
  - appnope=0.1.2
  - appscript=1.1.2
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - asn1crypto=1.4.0
  - astroid=2.4.2
  - astropy=4.2
  - async-timeout=3.0.1
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=20.3.0
  - autopep8=1.5.4
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - backports.shutil_get_terminal_size=1.0.0
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - beautifulsoup4=4.9.3
  - bitarray=1.6.3
  - bkcharts=0.2
  - black=19.10b0
  - blas=1.0
  - bleach=3.3.0
  - blinker=1.4
  - blosc=1.20.1
  - bokeh=2.2.3
  - boto=2.49.0
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - bumpversion=0.5.3
  - bwidget=1.9.11
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cachetools=4.2.1
  - cairo=1.14.12
  - cctools=927.0.2
  - certifi=2020.12.5
  - cffi=1.14.0
  - clang=10.0.0
  - clang_osx-64=10.0.0
  - clangxx=10.0.0
  - clangxx_osx-64=10.0.0
  - click=7.1.2
  - cloudpickle=1.6.0
  - clyent=1.2.2
  - cmarkgfm=0.5.3
  - colorama=0.4.4
  - compiler-rt=10.0.0
  - compiler-rt_osx-64=10.0.0
  - conda=4.10.0
  - conda-build=3.21.4
  - conda-env=2.6.0
  - conda-package-handling=1.7.2
  - conda-verify=3.4.2
  - configparser=5.0.2
  - contextlib2=0.6.0.post1
  - coverage=5.5
  - cryptography=3.3.1
  - curl=7.67.0
  - cycler=0.10.0
  - cython=0.29.21
  - cytoolz=0.11.0
  - dask=2021.1.1
  - dask-core=2021.1.1
  - dbus=1.13.18
  - debugpy=1.2.1
  - decorator=4.4.2
  - defusedxml=0.6.0
  - deprecated=1.2.10
  - diff-match-patch=20200713
  - distlib=0.3.1
  - distributed=2021.1.1
  - docstring_parser=0.7.3
  - docutils=0.16
  - elyra=1.5.3
  - entrypoints=0.3
  - et_xmlfile=1.0.1
  - expat=2.2.10
  - fastcache=1.1.0
  - filelock=3.0.12
  - flake8=3.8.4
  - flask=1.1.2
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - fsspec=0.8.3
  - future=0.18.2
  - get_terminal_size=1.0.0
  - gettext=0.19.8.1
  - gevent=21.1.1
  - gfortran_osx-64=4.8.5
  - gitdb=4.0.7
  - gitpython=3.1.14
  - glib=2.63.1
  - glob2=0.7
  - gmp=6.2.1
  - gmpy2=2.0.8
  - google-api-core=1.26.2
  - google-auth=1.28.0
  - google-cloud-core=1.5.0
  - google-cloud-storage=1.19.0
  - google-crc32c=1.1.2
  - google-resumable-media=1.2.0
  - googleapis-common-protos=1.53.0
  - graphite2=1.3.14
  - graphviz=2.40.1
  - greenlet=1.0.0
  - grpcio=1.36.1
  - gsl=2.4
  - h5py=2.10.0
  - harfbuzz=1.8.8
  - hdf5=1.10.4
  - heapdict=1.0.1
  - html5lib=1.1
  - icu=58.2
  - idna=2.10
  - imageio=2.9.0
  - imagesize=1.2.0
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - iniconfig=1.1.1
  - intel-openmp=2019.4
  - intervaltree=3.1.0
  - ipykernel=5.3.4
  - ipython=7.20.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - isort=5.7.0
  - itsdangerous=1.1.0
  - jbig=2.1
  - jdcal=1.4.1
  - jinja2=2.11.3
  - joblib=1.0.0
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter-packaging=0.7.12
  - jupyter_console=6.2.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.7.1
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.4.1
  - jupyter_server=1.4.1
  - jupyterlab=2.2.9
  - jupyterlab-git=0.23.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - jupyterlab_widgets=1.0.0
  - keyring=22.0.1
  - kfp=1.1.2
  - kfp-notebook=0.17.0
  - kfp-server-api=1.4.1
  - kiwisolver=1.3.1
  - krb5=1.16.4
  - lazy-object-proxy=1.4.3
  - lcms2=2.11
  - ld64=450.3
  - libarchive=3.4.2
  - libcrc32c=1.1.1
  - libcurl=7.67.0
  - libcxx=11.0.1
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc=4.8.5
  - libgfortran=3.0.1
  - libiconv=1.16
  - liblief=0.10.1
  - libllvm10=10.0.1
  - libllvm9=9.0.1
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libxml2=2.9.10
  - libxslt=1.1.34
  - llvm-openmp=10.0.0
  - llvmlite=0.34.0
  - locket=0.2.1
  - lxml=4.6.2
  - lz4-c=1.9.3
  - lzo=2.10
  - make=4.2.1
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mccabe=0.6.1
  - minio=6.0.2
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - mock=4.0.3
  - more-itertools=8.6.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.1.0
  - msgpack-python=1.0.2
  - multidict=5.1.0
  - multipledispatch=0.6.0
  - mypy_extensions=0.4.3
  - navigator-updater=0.2.1
  - nbclassic=0.2.6
  - nbconvert=5.6.1
  - nbdime=2.1.0
  - nbformat=5.1.2
  - nbresuse=0.4.0
  - ncurses=6.2
  - networkx=2.5
  - nltk=3.5
  - nodejs=6.13.1
  - nose=1.3.7
  - notebook=6.2.0
  - numba=0.51.2
  - numexpr=2.7.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - numpydoc=1.1.0
  - oauthlib=3.0.1
  - olefile=0.46
  - openpyxl=3.0.6
  - openssl=1.1.1k
  - packaging=20.9
  - pandoc=2.11
  - pandocfilters=1.4.3
  - pango=1.42.4
  - papermill=2.3.3
  - partd=1.1.0
  - path=15.1.0
  - path.py=12.5.0
  - pathlib2=2.3.5
  - pathspec=0.7.0
  - pathtools=0.1.2
  - patsy=0.5.1
  - pcre=8.44
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=20.3.3
  - pixman=0.40.0
  - pkginfo=1.7.0
  - pluggy=0.13.1
  - ply=3.11
  - prometheus_client=0.9.0
  - prompt_toolkit=3.0.8
  - protobuf=3.14.0
  - psutil=5.8.0
  - ptvsd=4.3.2
  - ptyprocess=0.7.0
  - py=1.10.0
  - py-lief=0.10.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycodestyle=2.6.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pycurl=7.43.0.5
  - pydocstyle=5.1.1
  - pyerfa=1.7.1.1
  - pyflakes=2.2.0
  - pyjwt=2.0.1
  - pylint=2.6.0
  - pyls-black=0.4.6
  - pyls-spyder=0.3.0
  - pyodbc=4.0.30
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=6.2.2
  - python=3.8.2
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.4.0
  - python-kubernetes=11.0.0
  - python-language-server=0.36.2
  - python-libarchive-c=2.9
  - python.app=3
  - python_abi=3.8
  - pytz=2021.1
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - qdarkstyle=2.8.1
  - qt=5.9.7
  - qtawesome=1.0.1
  - qtconsole=5.0.2
  - qtpy=1.9.0
  - r-askpass=1.0
  - r-assertthat=0.2.1
  - r-backports=1.1.4
  - r-base=3.6.1
  - r-base64enc=0.1_3
  - r-bh=1.69.0_1
  - r-boot=1.3_20
  - r-broom=0.5.2
  - r-callr=3.2.0
  - r-caret=6.0_83
  - r-cellranger=1.1.0
  - r-class=7.3_15
  - r-cli=1.1.0
  - r-clipr=0.6.0
  - r-cluster=2.0.8
  - r-codetools=0.2_16
  - r-colorspace=1.4_1
  - r-crayon=1.3.4
  - r-curl=3.3
  - r-data.table=1.12.2
  - r-dbi=1.0.0
  - r-dbplyr=1.4.0
  - r-dichromat=2.0_0
  - r-digest=0.6.18
  - r-dplyr=0.8.0.1
  - r-ellipsis=0.1.0
  - r-essentials=3.6.0
  - r-evaluate=0.13
  - r-fansi=0.4.0
  - r-forcats=0.4.0
  - r-foreach=1.4.4
  - r-foreign=0.8_71
  - r-formatr=1.6
  - r-fs=1.2.7
  - r-generics=0.0.2
  - r-ggplot2=3.1.1
  - r-glmnet=2.0_16
  - r-glue=1.3.1
  - r-gower=0.2.0
  - r-gtable=0.3.0
  - r-haven=2.1.0
  - r-hexbin=1.27.2
  - r-highr=0.8
  - r-hms=0.4.2
  - r-htmltools=0.3.6
  - r-htmlwidgets=1.3
  - r-httpuv=1.5.1
  - r-httr=1.4.0
  - r-ipred=0.9_8
  - r-irdisplay=0.7.0
  - r-irkernel=0.8.15
  - r-iterators=1.0.10
  - r-jsonlite=1.6
  - r-kernsmooth=2.23_15
  - r-knitr=1.22
  - r-labeling=0.3
  - r-later=0.8.0
  - r-lattice=0.20_38
  - r-lava=1.6.5
  - r-lazyeval=0.2.2
  - r-lubridate=1.7.4
  - r-magrittr=1.5
  - r-maps=3.3.0
  - r-markdown=0.9
  - r-mass=7.3_51.3
  - r-matrix=1.2_17
  - r-mgcv=1.8_28
  - r-mime=0.6
  - r-modelmetrics=1.2.2
  - r-modelr=0.1.4
  - r-munsell=0.5.0
  - r-nlme=3.1_139
  - r-nnet=7.3_12
  - r-numderiv=2016.8_1
  - r-openssl=1.3
  - r-pbdzmq=0.3_3
  - r-pillar=1.3.1
  - r-pkgconfig=2.0.2
  - r-plogr=0.2.0
  - r-plyr=1.8.4
  - r-prettyunits=1.0.2
  - r-processx=3.3.0
  - r-prodlim=2018.04.18
  - r-progress=1.2.0
  - r-promises=1.0.1
  - r-ps=1.3.0
  - r-purrr=0.3.2
  - r-quantmod=0.4_14
  - r-r6=2.4.0
  - r-randomforest=4.6_14
  - r-rbokeh=0.6.3
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.1
  - r-rcpproll=0.3.0
  - r-readr=1.3.1
  - r-readxl=1.3.1
  - r-recipes=0.1.5
  - r-recommended=3.6.0
  - r-rematch=1.0.1
  - r-repr=0.19.2
  - r-reprex=0.2.1
  - r-reshape2=1.4.3
  - r-rlang=0.3.4
  - r-rmarkdown=1.12
  - r-rpart=4.1_15
  - r-rstudioapi=0.10
  - r-rvest=0.3.3
  - r-scales=1.0.0
  - r-selectr=0.4_1
  - r-shiny=1.3.2
  - r-sourcetools=0.1.7
  - r-spatial=7.3_11
  - r-squarem=2017.10_1
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-survival=2.44_1.1
  - r-sys=3.2
  - r-tibble=2.1.1
  - r-tidyr=0.8.3
  - r-tidyselect=0.2.5
  - r-tidyverse=1.2.1
  - r-timedate=3043.102
  - r-tinytex=0.12
  - r-ttr=0.23_4
  - r-utf8=1.1.4
  - r-uuid=0.1_2
  - r-viridislite=0.3.0
  - r-whisker=0.3_2
  - r-withr=2.1.2
  - r-xfun=0.6
  - r-xml2=1.2.0
  - r-xtable=1.8_4
  - r-xts=0.11_2
  - r-yaml=2.2.0
  - r-zoo=1.8_6
  - readline=7.0
  - readme_renderer=27.0
  - regex=2020.11.13
  - requests-oauthlib=1.3.0
  - requests-toolbelt=0.9.1
  - rfc3986=1.4.0
  - rfc3986-validator=0.1.1
  - ripgrep=12.1.1
  - rope=0.18.0
  - rsa=4.7.2
  - rstudio=1.0.44
  - rtree=0.9.4
  - ruamel_yaml=0.15.87
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.6.0
  - send2trash=1.5.0
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.15.0
  - smmap=3.0.5
  - snappy=1.1.8
  - sniffio=1.2.0
  - snowballstemmer=2.1.0
  - sortedcollections=2.1.0
  - sortedcontainers=2.3.0
  - soupsieve=2.1
  - sphinx=3.4.3
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sphinxcontrib-websupport=1.2.4
  - spyder=4.2.1
  - spyder-kernels=1.10.1
  - sqlalchemy=1.3.23
  - sqlite=3.33.0
  - statsmodels=0.12.1
  - strip-hints=0.1.8
  - sympy=1.7.1
  - tapi=1000.10.8
  - tbb=2020.3
  - tblib=1.7.0
  - tenacity=7.0.0
  - terminado=0.9.2
  - testpath=0.4.4
  - textdistance=4.2.1
  - textwrap3=0.9.2
  - threadpoolctl=2.1.0
  - three-merge=0.1.1
  - tifffile=2020.10.1
  - tk=8.6.10
  - tktable=2.10
  - toml=0.10.1
  - toolz=0.11.1
  - tornado=6.1
  - tox=3.23.0
  - tqdm=4.56.0
  - traitlets=5.0.5
  - twine=3.3.0
  - typed-ast=1.4.2
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - ujson=4.0.2
  - unicodecsv=0.14.1
  - unixodbc=2.3.9
  - urllib3=1.26.3
  - watchdog=1.0.2
  - wcwidth=0.2.5
  - websocket-client=0.57.0
  - werkzeug=1.0.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - wurlitzer=2.0.1
  - xeus=1.0.1
  - xeus-python=0.11.2
  - xlrd=2.0.1
  - xlsxwriter=1.3.7
  - xlwings=0.22.0
  - xlwt=1.3.0
  - xmltodict=0.12.0
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.30.0
  - yarl=1.6.3
  - zeromq=4.3.3
  - zict=2.0.0
  - zipp=3.4.0
  - zlib=1.2.11
  - zope=1.0
  - zope.event=4.5.0
  - zope.interface=5.2.0
  - zstd=1.4.5
  - pip:
    - aiohttp==3.7.3
    - appdirs==1.4.4
    - arch==4.16.1
    - azure-core==1.12.0
    - azure-storage-blob==12.8.0
    - bandit==1.7.0
    - bayesian-bootstrap==1.0.5
    - chardet==3.0.4
    - dataesg==0.0.1
    - dataproperty==0.50.0
    - dc-stat-think==1.1.1
    - diagrams==0.19.1
    - dicttoxml==1.7.4
    - gender-guesser==0.4.0
    - gnureadline==8.0.0
    - ipyparallel==6.3.0
    - isodate==0.6.0
    - jedi==0.18.0
    - jikanpy==4.3.0
    - jupyter-client==6.1.11
    - jupyter-pip==0.3.1
    - jupyterthemes==0.20.0
    - lesscpy==0.14.0
    - mbstrdecoder==1.0.1
    - msgfy==0.1.0
    - msrest==0.6.21
    - multitasking==0.0.9
    - nb2xls==0.1.6
    - nbclient==0.5.3
    - nest-asyncio==1.5.1
    - pandas==1.1.5
    - pandoc-shortcaption==1.2
    - parso==0.8.1
    - pathvalidate==2.3.2
    - pbr==5.5.1
    - prompt-toolkit==3.0.16
    - property-cached==1.6.4
    - pygments==2.8.1
    - pypng==0.0.20
    - pystout==0.0.5
    - pytablewriter==0.58.0
    - python-graphviz==0.16
    - pyzmq==22.0.3
    - qgrid==1.3.1
    - requests==2.25.0
    - seaborn==0.11.0
    - selenium==3.141.0
    - setuptools==54.1.1
    - simplejson==3.17.2
    - stargazer==0.0.5
    - stevedore==3.3.0
    - tabledata==1.1.3
    - tabulate==0.8.7
    - tcolorpy==0.0.8
    - typepy==1.1.4
    - virtualenv==20.4.0
    - wbdata==0.3.0
    - webencodings==0.5.1
    - yfinance==0.1.55
