name: base
channels:
  - defaults
dependencies:
  - conda
  - python=3.8
  - python.app
  - conda-env
  - conda-build
  - conda-verify
  - _ipyw_jlab_nb_ext_conf
  - anaconda
  - anaconda-navigator
  - navigator-updater
  - jupyter_contrib_nbextensions
  - nbconvert
  - rstudio
  - r-caret
  - graphviz
  - jupyterlab=2
  - xeus-python
  - ptvsd
  - elyra
